name: Deploy Front-end

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BASE_URL: ${{ vars.BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          git config user.email nick-ng@users.noreply.github.com
          git config user.name "${GITHUB_ACTOR}"
          npm i --ignore-scripts
          npm run build
          cp ./build/index.html ./build/404.html
          if [[ $BASE_URL ]]; then
            echo $BASE_URL > ./build/CNAME
          else
            echo "export const trailingSlash = 'never';" >> src\routes\+layout.ts
          fi
          git checkout --orphan gh-pages
          git reset
          cp -R ./build/. ./
          git add $(ls ./build)
          touch .nojekyll
          git add .nojekyll
          git commit -m "$(date) deploy front-end"
          git push --force origin gh-pages
